Work in progress Fri Aug 29 16:14:07 CEST 2025

diff --git a/.github/workflows/cluster.omni.yaml b/.github/workflows/cluster.omni.yaml
--- a/.github/workflows/cluster.omni.yaml
+++ b/.github/workflows/cluster.omni.yaml
@@ -135,12 +135,12 @@ jobs:
           # Check if kube-apiserver is ready
 
           until kubectl get ns kube-system >/dev/null 2>&1; do
-            if [ $COUNT -gt 10 ]; then
-              echo "ERROR: Timed out waiting for kube-apiserver"
-              exit 1
-            fi
-            
             echo "Waiting for kube-apiserver to be ready... (Attempt $COUNT)"
             sleep 5
             COUNT=$((COUNT + 1))
+            
+            if [ $COUNT -eq 10 ]; then
+              echo "ERROR: Timed out waiting for kube-apiserver"
+              exit 1
+            fi
           done;
